apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-graphql-app
  namespace: go-api-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-graphql-app
  template:
    metadata:
      labels:
        app: go-graphql-app
    spec:
      containers:
        - name: go-graphql-app
          image: lokinious/go-graphql-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-graphql-app
  namespace: go-api-practice
spec:
  selector:
    app: go-graphql-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
